"""empty message

Revision ID: 1fbe5dcf2b5d
Revises: 71a1042cb75d
Create Date: 2021-05-18 12:33:47.611817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbe5dcf2b5d'
down_revision = '71a1042cb75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('newCustomerName', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('newCustomerPhone', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('newCustomerPostalCode', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('newCustomerVideosCheckedOut', sa.Integer(), nullable=True))
    op.drop_column('customers', 'name')
    op.drop_column('customers', 'videos_checked_out_count')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'newCustomerVideosCheckedOut')
    op.drop_column('customers', 'newCustomerPostalCode')
    op.drop_column('customers', 'newCustomerPhone')
    op.drop_column('customers', 'newCustomerName')
    # ### end Alembic commands ###
