"""empty message

Revision ID: 71a1042cb75d
Revises: eee9fe077fff
Create Date: 2021-05-18 11:26:22.595089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a1042cb75d'
down_revision = 'eee9fe077fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'registered_at')
    # ### end Alembic commands ###
