"""empty message

Revision ID: eee9fe077fff
Revises: 78ad7abc647c
Create Date: 2021-05-18 11:16:56.353679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee9fe077fff'
down_revision = '78ad7abc647c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'videos_checked_out_count')
    # ### end Alembic commands ###
