"""empty message

Revision ID: f27875936f28
Revises: 1d951dff7871
Create Date: 2021-05-19 09:31:28.652095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27875936f28'
down_revision = '1d951dff7871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('v_id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['v_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id', 'v_id', 'c_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###
